### PR TITLE
Release artifacts for release `v0.0.20`

### PR DESCRIPTION
**Pull request by A-Hilaly**
Release artifacts for release `v0.0.20`

Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
need merge after #30 
/hold

**Review by vijtrip2 — APPROVED** [review]

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
